version: '3.8'

volumes:
  mysql_data:


services:
  database:
    image: mysql:latest
    container_name: temperature_database
    environment:
      MYSQL_ROOT_PASSWORD: bob
      MYSQL_DATABASE: temperature_database
      MYSQL_USER: bob
      MYSQL_PASSWORD: bob
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - temperature_network

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    container_name: my_backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - temperature_network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.frontend
    container_name: my_frontend
    ports:
      - "80:80"
    networks:
      - temperature_network

networks:
  temperature_network:
    driver: bridge
