FROM node:14

RUN apt update && apt install -y netcat

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

COPY wait_for_it.sh /wait_for_it.sh

RUN chmod +x /wait_for_it.sh

EXPOSE 3000

# CMD ["node", "server.js"]
CMD ["./wait_for_it.sh", "database", "3306", "--", "node", "server.js"]
